#!/usr/bin/env rake
# encoding: utf-8
# PGonror is the corporate web site framework of Le Parti de Gauche based on Ruby on Rails.
# 
# Copyright (C) 2013 Le Parti de Gauche
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# 
# See doc/COPYRIGHT.rdoc for more details.
include ActionView::Helpers::DateHelper

namespace :app do
  desc 'Application status'
  task :status => :environment do
    puts "- Application status."
    last = User.last ; puts "-- Users: #{User.count} | #{last.present? ? (last.email + ',' + last.updated_at.to_s) : ''}"
    last = Permission.last ; puts "-- Permission: #{Permission.count} | #{last.present? ? (last.updated_at.to_s) : ''}"
    last = Article.last; puts "-- Articles: #{Article.count} | #{last.present? ? (last.title + ',' + last.updated_at.to_s) : ''}"
    categories = Article.find_by_status_group_by_category Article::ONLINE
    for category in categories
      puts "--- #{category[1]} : #{category[2]}"
    end
    last = Audit.last; puts "-- Audits #{Audit.count} | #{last.present? ? (last.updated_at.to_s) : ''}"
    last = Tag.last; puts "-- Tags: #{Tag.count} | #{last.present? ? (last.tag + ',' + last.updated_at.to_s) : ''}"
    last = Donation.last; puts "-- Donations: #{Donation.count} | #{last.present? ? (last.first_name + ' ' + last.last_name + ',' + last.updated_at.to_s) : ''}"
    last = Membership.last; puts "-- Membership: #{Membership.count} | #{last.present? ? (last.first_name + ' ' + last.last_name + ',' + last.updated_at.to_s) : ''}"
    last = Request.last; puts "-- Requests: #{Request.count} | #{last.present? ? (last.first_name + ' ' + last.last_name + ',' + last.updated_at.to_s) : ''}"
    last = Subscription.last; puts "-- Subscriptions: #{Subscription.count} | #{last.present? ? (last.first_name + ' ' + last.last_name + ',' + last.updated_at.to_s) : ''}"
  end

  desc 'Restarts server'
  task :restart do
    sh 'touch tmp/restart.txt'
  end

  desc 'Update status for old articles'
  task :update_old_status => :environment do
    for article in Article.where('(status is null or status in (?,?,?)) and updated_at < ?',
                  Article::NEW,
                  Article::REWORK,
                  Article::REVIEWED,
                  Time.now - 1.month)
      puts "-- Update article '#{article.title}'"
      article.transaction do
        article.updated_by = "[Auto]"
        article.status = (['image', 'document'].include?(article.category) ? Article::ONLINE : Article::OFFLINE)
        article.save!
        article.create_audit! article.status, article.updated_by
      end
    end
  end

  desc 'Update data quality'
  task :update_data_quality => :environment do
    for article in Article.where("title like ' %' or title like '% ' or title like '%.' or title like '%:' or title like '%-'")
      puts "-- Update article title '#{article.title}'"
      id = article.id
      title = article.title.strip
      for i in 1..100 ; title = title.gsub(/(.*)[\.:-]$/, "\\1") end
      ActiveRecord::Base.connection.execute "update articles set title = #{Article.quote(title)} where id = #{id}"
    end

    for article in Article.where("heading like ' %' or heading like '% ' or heading like '%.' or heading like '%:' or heading like '%-'")
      puts "-- Update article heading '#{article.heading}' - '#{article.title}'"
      id = article.id
      heading = article.heading.strip
      for i in 1..100 ; heading = heading.gsub(/(.*)[\.:-]$/, "\\1") end
      ActiveRecord::Base.connection.execute "update articles set heading = #{Article.quote(heading)} where id = #{id}"
    end

    for article in Article.where("signature like ' %' or signature like '% ' or signature like '%.' or signature like '%:' or signature like '%-' or signature like '%&%' or signature like '%  %'")
      puts "-- Update article signature '#{article.signature}' - '#{article.title}'"
      id = article.id
      signature = article.signature.strip
      for i in 1..100 ; signature = signature.gsub(/(.*)[\.:-]$/, "\\1").gsub(/&/, "et").gsub(/\s\s/, " ") end
      ActiveRecord::Base.connection.execute "update articles set signature = #{Article.quote(signature)} where id = #{id}"
    end
    
    for signature in [
      ["AFP / JEAN-SEBASTIEN EVRARD", "Jean-Sébastien Evrard, AFP"],
      ["AFP/BERTRAND GUAY", "Bertrand Guay, AFP"],
      ["Alain BILLON", "Alain Billon"],
      ["Aissa TERCHI, Leila HADJ-JO, Sophie COUDERT", "Aissa Terchi, Leila Hadj-Jo, Sophie Coudert"],
      ["Alexis Corbiere", "Alexis Corbière"],
      ["Alexis CORBIERE", "Alexis Corbière"],
      ["Alexis Corbiere et Danielle Simonnet", "Alexis Corbière et Danielle Simonnet"],
      ["Alexis TSIPRAS", "Alexis Tsipras"],
      ["Aliki PAPADOMICHELAKI", "Aliki Papadomichelaki"],
      ["Anne Saidi", "Anne Saïdi"],
      ["Anne-Marie LIKIERNIK", "Anne-Marie Likiernik"],
      ["Anny SIRE-RICHARD", "Anny Sire-Richard"],
      ["Audray Galland", "Audrey Galland"],
      ["Benoit Schneckenburger", "Benoît Schneckenburger"],
      ["Benoît Schenckenburger", "Benoît Schneckenburger"],
      ["Bruno Fiallho", "Bruno Fialho"],
      ["Bruno ONDO MINTSA, Benjamin BIBAS, Patrice FINEL, Juliette Poirson", "Bruno Ondo Mintsa, Benjamin Bibas, Patrice Finel, Juliette Poirson"],
      ["Bureau National", "Bureau National du Parti de Gauche"],
      ["Bureau national", "Bureau National du Parti de Gauche"],
      ["CHAIBI Leïla", "Leila Chaibi"],
      ["COLLECTIF D’ÉLUS, MILITANTS ET CITOYENS de Drôme, Vaucluse, Ardèche et d'ailleurs", "Collectif d’élus, militants et citoyens de Drôme, Vaucluse, Ardèche et d'ailleurs"],
      ["Catherine GUILLAUME", "Catherine Guillaume"],
      ["Catherine Jouaneau", "Catherine Jouanneau"],
      ["Catherine jouanneau", "Catherine Jouanneau"],
      ["Celine MENESES", "Céline Meneses"],
      ["Christian DUVINAGE", "Christian Duvinage"],
      ["Christian FAVIER", "Christian Favier"],
      ["Christian PICQUET", "Christian Picquet"],
      ["Christiane CHOMBEAU", "Christiane Chombeau"],
      ["Christiophe RAMAUX", "Christophe Ramaux"],
      ["Christophe MIQUEU", "Christophe Miqueu"],
      ["Christophe RAMAUX", "Christophe Ramaux"],
      ["Christophe VENTURA", "Christophe Ventura"],
      ["Christophe ventura", "Christophe Ventura"],
      ["Claude DEBONS", "Claude Debons"],
      ["Claude DEBONS et Jacques GENEREUX", "Claude Debons et Jacques Généreux"],
      ["Commission Afrique du Secteur International du Parti de Gauche", "Commission Afrique du Secteur international du Parti de Gauche"],
      ["Commission Internationale", "Commission International"],
      ["Communique du Parti de Gauche", "Le Parti de Gauche"],
      ["Communiqué de Jean-Luc Mélenchon", "Jean-Luc Mélenchon"],
      ["Communiqué de Martine Billard, Co-Présidente du Parti de Gauche", "Martine Billard, Co-Présidente du Parti de Gauche"],
      ["Communiqué de la Commission Outre-mer du Parti de Gauche et des Comités de la Guadeloupe, de la Martinique, de la Réunion et de la Guyane", "Commission Outre-mer du Parti de Gauche et des Comités de la Guadeloupe, de la Martinique, de la Réunion et de la Guyane"],
      ["Communiqué du PG", "Le Parti de Gauche"],
      ["Communiqué du Parti de Gauche", "Le Parti de Gauche"],
      ["Comuniqué du PG", "Le Parti de Gauche"],
      ["Conseil National", "Conseil national du Parti de Gauche"],
      ["Conseil National du PG", "Conseil national du Parti de Gauche"],
      ["Conseil national", "Conseil national du Parti de Gauche"],
      ["Conseillers de paris PG", "Conseillers de Paris PG"],
      ["Conseiol National du PG", "Conseil national du Parti de Gauche"],
      ["Corine Morel Darleux", "Corinne Morel Darleux"],
      ["Corine Morel--Darleux", "Corinne Morel Darleux"],
      ["Corinne MOREL DARLEUX", "Corinne Morel Darleux"],
      ["Corinne MOREL DARLEUX, Secrétaire nationale à l'écologie du Parti de Gauche", "Corinne Morel Darleux, Secrétaire nationale à l'écologie du Parti de Gauche"],
      ["Corinne MOREL DARLEUX, Secrétaire nationale à l'écosocialisme, Laurence PACHE, Secrétaire nationale aux Transports et à l'organisation territoriale", "Corinne Morel Darleux, Secrétaire nationale à l'écosocialisme, Laurence Pache, Secrétaire nationale aux Transports et à l'organisation territoriale"],
      ["Corinne Morel-Darleux", "Corinne Morel Darleux"],
      ["Corinne Morel-Darleux et Christophe Ventura", "Corinne Morel Darleux et Christophe Ventura"],
      ["Corinne Morel-Darleux et Céline Meneses", "Corinne Morel Darleux et Céline Meneses"],
      ["Céline MENESES, secrétariat international", "Céline Meneses, secrétariat international"],
      ["DEPUTE-E-S COMMUNISTES, REPUBLICAINS, DU PARTI DE GAUCHE", "Député-e-s Communistes, Républicains, du Parti de Gauche"],
      ["Danielle SIMONNET", "Danielle Simonnet"],
      ["Danielle SIMONNET, Conseillère de Paris et Secrétaire nationale aux migrations du Parti de Gauche", "Danielle Simonnet, Conseillère de Paris et Secrétaire nationale aux migrations du Parti de Gauche"],
      ["Danielle Simonet et Franck Pupunat", "Danielle Simonnet et Franck Pupunat"],
      ["Danielle Simonnet et Eric Cocquerel", "Danielle Simonnet et Eric Coquerel"],
      ["Delphine BEAUVOIS", "Delphine Beauvois"],
      ["Delphine BEAUVOIS, Secrétaire nationale à l'Egalité Femmes-Hommes", "Delphine Beauvois, Secrétaire nationale à l'Egalité Femmes-Hommes"],
      ["Elodie VAXELAIRE", "Elodie Vaxelaire"],
      ["Eléni FERLET et Céline MENESES", "Elène Ferlet et Céline Meneses"],
      ["Emmanuel VERGÉ", "Emmanuel Vergé"],
      ["Eoldie Vaxelaire", "Elodie Vaxelaire"],
      ["Eric COQUEREL", "Eric Coquerel"],
      ["FdG", "Le Front de Gauche"],
      ["Frainçois Delapierre", "François Delapierre"],
      ["Francis DASPE", "Francis Daspe"],
      ["Franck PUPUNAT", "Franck Pupunat"],
      ["Franàçois Delapierre", "François Delapierre"],
      ["François AUTAIN", "François Autain"],
      ["François AUTAIN, Jean-Luc MELENCHON", "François Autain, Jean-Luc Mélenchon"],
      ["François BERGER", "François Berger"],
      ["François COCQ", "François Cocq"],
      ["François COCQ et Francis DASPE", "François Cocq et Francis Daspe"],
      ["François COCQ, Francis DASPE", "François Cocq et Francis Daspe"],
      ["François COCQ, Magali ESCOT", "François Cocq, Magali Escot"],
      ["François COCQ, Pierre CHANTELOT", "François Cocq, Pierre Chantelot"],
      ["François COCQ, Secrétaire national à l’éducation, au Service Public et à la formation", "François Cocq, Secrétaire national à l’éducation, au Service Public et à la formation"],
      ["François Coc", "François Cocq"],
      ["François Cocq, Francis Daspe", "François Cocq et Francis Daspe"],
      ["François Coq", "François Cocq"],
      ["François Coq et Francis Daspe", "François Cocq et Francis Daspe"],
      ["François DELAPIERRE", "François Delapierre"],
      ["François Delapierre Eric Coquerel", "François Delapierre et Eric Coquerel"],
      ["François Farbeau,militant du PG à Londres", "François Farbeau, militant du PG à Londres"],
      ["François Farbeau, militant PG à Londres", "François Farbeau, militant du PG à Londres"],
      ["François LONGERINAS", "François Longérinas"],
      ["François RUFFIN", "François Ruffin"],
      ["Françoise VERCHERE, conseillère générale de Loire-Atlantique", "Françoise Verchère, Conseillère générale de Loire-Atlantique"],
      ["Françosi COCQ", "François Cocq"],
      ["Front de Gauche 67", "Le Front de Gauche 67"],
      ["Front de Gauche 95", "Le Front de Gauche 95"],
      ["Front de Gauche Afrique", "Le Front de Gauche Afrique"],
      ["Front de Gauche Cergy", "Le Front de Gauche Cergy"],
      ["Front de Gauche Espagne / Comité Méditerranée des Français de l'étranger du Parti de Gauche", "Le Front de Gauche Espagne / Comité Méditerranée des Français de l'étranger du Parti de Gauche"],
      ["Front de Gauche Féministe", "Le Front de Gauche Féministe"],
      ["Front de Gauche LGBT", "Le Front de Gauche LGBT"],
      ["Front de Gauche Latino, Les amis de l'Usine, Alerte Honduras", "Le Front de Gauche Latino, Les amis de l'Usine, Alerte Honduras"],
      ["Front de Gauche Picardie", "Le Front de Gauche Picardie"],
      ["Front de Gauche de l'Agriculture", "Le Front de Gauche de l'Agriculture"],
      ["Front de Gauche des luttes", "Le Front de Gauche des luttes"],
      ["Front de Gauche du Morbihan", "Le Front de Gauche du Morbihan"],
      ["Front de Gauche et LGBT", "Le Front de Gauche et LGBT"],
      ["Front des Luttes", "Le Front des Luttes"],
      ["Front-de-Gauche", "Le Front de Gauche"],
      ["Florence POZNANSKI et Eduardo MENESES", "Florence Poznanski et Eduardo Meneses"],
      ["Frédéric ALLIOT", "Frédéric Alliot"],
      ["Frédéric ALLIOT et Jacques DESALLANGRE", "Frédéric Alliot et Jacques Desallangre"],
      ["Frédéric PLUCHON", "Frédéric Pluchon"],
      ["Gabriel AMARD", "Gabriel Amard"],
      ["Galila ELKADI", "Galila El Kadi"],
      ["Groupe Front de Gauche et Alternatifs du Conseil régional d'Ile de France", "Groupe Front de Gauche et Alternatifs du Conseil Régional d'Ile-de-France"],
      ["Groupe Front de Gauche et Alternatifs de la région IdF", "Groupe Front de Gauche et Alternatifs du Conseil Régional d'Ile-de-France"],
      ["Guy QUEYTAN", "Guy Queytan"],
      ["Guy Quetan", "Guy Queytan"],
      ["Haydée MARTIN", "Haydée Martin"],
      ["Henri PENA RUIZ", "Henri Peña-Ruiz"],
      ["Henri Pena Ruiz", "Henri Peña-Ruiz"],
      ["Henri Pena-Ruiz", "Henri Peña-Ruiz"],
      ["Henri Peña Ruiz", "Henri Peña-Ruiz"],
      ["Hervé BOYER", "Hervé Boyer"],
      ["Hervé EON", "Hervé Eon"],
      ["Hervé LAVISSE", "Hervé Lavisse"],
      ["Humanité.fr", "Humanite.fr"],
      ["Hélène COUSSEAU", "Hélène Cousseau"],
      ["Hélène FRANCO", "Hélène Franco"],
      ["JEAN DE PEÑA, SOPHIE CHAPELLE", "Jean de Peña, Sophie Chapelle"],
      ["Jacque sDesallangre", "Jacques Desallangre"],
      ["Jacques Desalangre", "Jacques Desallangre"],
      ["Jacques Dessalangre", "Jacques Desallangre"],
      ["Jacques Dessallangre", "Jacques Desallangre"],
      ["Jacques GLEIZES (cheminot PG à Béziers) et Nicolas VOISIN (BN PG)", "Jacques Gleizes (cheminot PG à Béziers) et Nicolas Voisin (BN PG)"],
      ["Jacques GÉNÉREUX, secrétaire national à l'économie", "Jacques Généreux, secrétaire national à l'économie"],
      ["Jacques RIGAUDIAT", "Jacques Rigaudiat"],
      ["Jean Claude COS et Christine LE COENT, co - secrétaires du Comité Lille Métropole", "Jean Claude Cos et Christine Le Coent, co - secrétaires du Comité Lille Métropole"],
      ["Jean ESTIVILL, Conseiller municipal, Président des élus du Parti de Gauche de Savigny sur Orge, Président de l’ARAC", "Jean Estivill, Conseiller municipal, Président des élus du Parti de Gauche de Savigny sur Orge, Président de l’ARAC"],
      ["Jean Luc Mélechon", "Jean-Luc Mélenchon"],
      ["Jean Luc Mélenchon", "Jean-Luc Mélenchon"],
      ["Jean Luc Mélenchon - Co-Président du Parti de Gauche", "Jean-Luc Mélenchon, Co-Président du Parti de Gauche"],
      ["Jean Luc Mélenchon - Co-Président du Parti de Gauche, Député Européen du Front de Gauche", "Jean-Luc Mélenchon, Co-Président du Parti de Gauche, Député Européen du Front de Gauche"],
      ["Jean Luc Mélenchon - Député Européen", "Jean-Luc Mélenchon, Député Européen"],
      ["Jean Luc Mélenchon - Député Européen du Front de Gauche", "Jean Luc Mélenchon, Député Européen"],
      ["Jean Luc Mélenchon et Céline Meneses", "Jean-Luc Mélenchon et Céline Meneses"],
      ["Jean Luc Mélenchon et Sakina Faouzi", "Jean-Luc Mélenchon et Sakina Faouzi"],
      ["Jean Luc Mélenchon, député Européen", "Jean-Luc Mélenchon, Député Européen"],
      ["Jean NICOLAS", "Jean Nicolas"],
      ["Jean-Charles Lallemand et Pascale Le Neouannic", "Jean-Charles Lallemand et Pascale Le Néouannic"],
      ["Jean-Charles Lallemand, Pascale Le Neouannic", "Jean-Charles Lallemand et Pascale Le Néouannic"],
      ["Jean-Charles Lallemand, Secrétaire national à l’égalité des droits,", "Jean-Charles Lallemand, Secrétaire national à l’égalité des droits"],
      ["Jean-Claude GAWSEWITCH", "Jean-Claude Gawsewitch"],
      ["Jean-Luc MELENCHON", "Jean-Luc Mélenchon"],
      ["Jean-Luc MELENCHON et Ignacio RAMONET", "Jean-Luc Mélenchon et Ignacio Ramonet"],
      ["Jean-Luc Mélechon", "Jean-Luc Mélenchon"],
      ["Jean-Luc Mélnchon", "Jean-Luc Mélenchon"],
      ["Jean-Luc Mélenchon, Député européen", "Jean-Luc Mélenchon, Député Européen"],
      ["Jean-Luc VARIN", "Jean-Luc Varin"],
      ["JeanLuc Mélenchon", "Jean-Luc Mélenchon"],
      ["JeanMarc Frouard", "Jean-Marc Frouard"],
      ["Jeannick LE LAGADEC", "Jeannick Le Lagadec"],
      ["Jo ROSSIGNOL", "Jo Rossignol"],
      ["Joelle ELLERT", "Joëlle Ellert"],
      ["Joëlle ELLERT", "Joëlle Ellert"],
      ["Juliette PRADOS", "Juliette Prados"],
      ["L'Humanité.fr", "humanite.fr"],
      ["La Commission Défense et Céline Meneses", "Commission Défense et Céline Meneses"],
      ["La commission Amérique Latine du PG", "Commission Amérique Latine"],
      ["La commission défense du Parti de Gauche", "Commission Défense"],
      ["Laurence sauvage", "Laurence Sauvage"],
      ["Laurent AYRAULT", "Laurent Ayrault"],
      ["Laurent Bordeaux", "Laurent Bordeau"],
      ["Laurent LEVARD", "Laurent Levard"],
      ["Laurent MAFEIS", "Laurent Maffeïs"],
      ["Laurent MAFFEÏS", "Laurent Maffeïs"],
      ["Laurent Mafeïs", "Laurent Maffeïs"],
      ["Laurent Maféis", "Laurent Maffeïs"],
      ["Front de Gauche 44", "Le Front de Gauche 44"],
      ["Le Front de gauche", "Le Front de Gauche"],
      ["Front de gauche", "Le Front de Gauche"],
      ["Le Parti de Gauche de Loire Atlantique", "Le Parti de Gauche de Loire-Atlantique"],
      ["Parti de Gauche de Loire-Atlantique", "Le Parti de Gauche de Loire-Atlantique"],
      ["Le Parti de Gauche du Val d'Oise", "Parti de Gauche du Val d'Oise"],
      ["Parti de Gauche du Val d'Oise", "Le Parti de Gauche du Val d'Oise"],
      ["Parti de Gauche d’Aulnay sous Bois", "Le Parti de Gauche d’Aulnay sous Bois"],
      ["Le Parti de gauche", "Le Parti de Gauche"],
      ["Le Parti-de-Gauche77", "Le Parti de Gauche 77"],
      ["Parti-de-Gauche77", "Le Parti de Gauche 77"],
      ["Le parti de Gauche du Bas Rhin", "Le Parti de Gauche du Bas Rhin"],
      ["Parti de Gauche du Bas Rhin", "Le Parti de Gauche du Bas Rhin"],
      ["Leila CHAIBI", "Leila Chaibi"],
      ["Leïla CHAIBI", "Leila Chaibi"],
      ["Luis CASADO", "Luis Casado"],
      ["MARTINE BILLARD", "Martine Billard"],
      ["Magali ESCOT, Christophe VENTURA, Alain BILLON, représentants du Parti de Gauche au FSM", "Magali Escot, Christophe Ventura, Alain Billon, représentants du Parti de Gauche au FSM"],
      ["Magali ESCOT, responsable éducation", "Magali Escot, responsable éducation"],
      ["Magalli Escot, Jean Sicard; photos: Raphaël", "Magali Escot, Jean Sicard; photos: Raphaël"],
      ["Marie Agnès LABARRE, Corinne MOREL DARLEUX", "Marie-Agnès Labarre, Corinne Morel Darleux"],
      ["Marie Agnès Labarre", "Marie-Agnès Labarre"],
      ["Martien Billard", "Martine Billard"],
      ["Martine BILLARD", "Martine Billard"],
      ["Martine Billard, Coprésidente du Parti de Gauche", "Martine Billard, Co-Présidente du Parti de Gauche"],
      ["Martine Billard, co présidente du Parti de Gauche", "Martine Billard, Co-Présidente du Parti de Gauche"],
      ["Martine Billard, co-présidente du Parti de Gauche", "Martine Billard, Co-Présidente du Parti de Gauche"],
      ["Martine Billard, co-présidente du Parti de Gauche et Mathieu Agostini membre du Bureau National en charge de l'écologie", "Martine Billard, Co-Présidente du Parti de Gauche et Mathieu Agostini membre du Bureau National en charge de l'écologie"],
      ["Mathieu AGOSTINI", "Mathieu Agostini"],
      ["Mathieu AGOSTINI et Corinne MOREL DARLEUX", "Mathieu Agostini et Corinne Morel Darleux"],
      ["Mathieu Agostini, Corinne Morel-Darleux, Christophe Ventura", "Mathieu Agostini, Corinne Morel Darleux, Christophe Ventura"],
      ["Matthieu AUZANNEAU, journaliste indépendant", "Matthieu Auzanneau, journaliste indépendant"],
      ["Matthieu Agostini", "Mathieu Agostini"],
      ["Meneses Céline", "Céline Meneses"],
      ["Michel PINÇON et Monique PINÇON-CHARLOT", "Michel Pinçon et Monique Pinçon-Charlot"],
      ["Mounia BENAILI", "Mounia Benaili"],
      ["Nathanael UHL", "Nathanaël Uhl"],
      ["Nathanael Uhl", "Nathanaël Uhl"],
      ["Nathanaël UHL", "Nathanaël Uhl"],
      ["Nicolas VOISIN", "Nicolas Voisin"],
      ["Nicolas VOISIN et Juliette PRADOS", "Nicolas Voisin et Juliette Prados"],
      ["Oskar Lafontaine -Jean-Luc Mélenchon", "Oskar Lafontaine et Jean-Luc Mélenchon"],
      ["PARTI DE GAUCHE – SECTEUR INTERNATIONAL", "Commission International"],
      ["PASCAL POCHARD-CASABIANCA / AFP", "Pascal Pochard-Casabianca / AFP"],
      ["PG", "Le Parti de Gauche"],
      ["Par David Cayla", "David Cayla"],
      ["Par Francisco Dominguez, secrétaire de Venezuela Solidarity Campaign traduction de Jennifer Smyth", "Francisco Dominguez, secrétaire de Venezuela Solidarity Campaign traduction de Jennifer Smyth"],
      ["Parti de Ganche", "Le Parti de Gauche"],
      ["Parti de gauche", "Le Parti de Gauche"],
      ["Parti de la gauche européenne", "Parti de la Gauche Européenne"],
      ["Parti-de-Gauche", "Le Parti de Gauche"],
      ["PG 13", "Le Parti de Gauche 13"],
      ["PG 20", "Le Parti de Gauche 20"],
      ["PG 22", "Le Parti de Gauche 22"],
      ["PG 33", "Le Parti de Gauche 33"],
      ["PG 44", "Le Parti de Gauche 44"],
      ["PG 75", "Le Parti de Gauche 75"],
      ["PG 93", "Le Parti de Gauche 93"],
      ["PG Ain", "Le Parti de Gauche Ain"],
      ["PG Alpes de Haute Provence", "Le Parti de Gauche Alpes de Haute Provence"],
      ["PG Ardèche", "Le Parti de Gauche Ardèche"],
      ["PG Bas-Rhin", "Le Parti de Gauche Bas-Rhin"],
      ["PG Dijon Jeunes", "Le Parti de Gauche Dijon Jeunes"],
      ["PG Drôme", "Le Parti de Gauche Drôme"],
      ["PG Dunkerque", "Le Parti de Gauche Dunkerque"],
      ["PG Les Alternatifs", "Le Parti de Gauche Les Alternatifs"],
      ["PG Savoie", "Le Parti de Gauche Savoie"],
      ["PG Val d'Oise", "Le Parti de Gauche Val d'Oise"],
      ["PG de Bretagne", "Le Parti de Gauche de Bretagne"],
      ["PG38", "Le Parti de Gauche 38"],
      ["PG53", "Le Parti de Gauche 53"],
      ["PG68", "Le Parti de Gauche 68"],
      ["PG77", "Le Parti de Gauche 77"],
      ["PG81 - Tarn", "Le Parti de Gauche 81"],
      ["PGE", "Parti de la Gauche Européenne"],
      ["Parti de Gauche - Département des Français de l'étranger", "Le Parti de Gauche, département des Français de l'étranger"],
      ["Parti de Gauche 07", "Le Parti de Gauche 07"],
      ["Parti de Gauche 19", "Le Parti de Gauche 19"],
      ["Parti de Gauche 22", "Le Parti de Gauche 22"],
      ["Parti de Gauche 44, NPA 44 et Alternatifs 44", "Le Parti de Gauche 44, NPA 44 et Alternatifs 44"],
      ["Parti de Gauche 67", "Le Parti de Gauche 67"],
      ["Parti de Gauche 67, Josiane Nervi-Gasparini, Jean-Claude Val", "Le Parti de Gauche 67, Josiane Nervi-Gasparini, Jean-Claude Val"],
      ["Parti de Gauche 75", "Le Parti de Gauche 75"],
      ["Parti de Gauche 77", "Le Parti de Gauche 77"],
      ["Parti de Gauche 92", "Le Parti de Gauche 92"],
      ["Parti de Gauche 93", "Le Parti de Gauche 93"],
      ["Parti de Gauche 95", "Le Parti de Gauche 95"],
      ["Parti de Gauche Aveyron", "Le Parti de Gauche Aveyron"],
      ["Parti de Gauche Europe du Nord", "Le Parti de Gauche Europe du Nord"],
      ["Parti de Gauche Londres", "Le Parti de Gauche Londres"],
      ["Parti de Gauche Seine maritime", "Le Parti de Gauche Seine maritime"],
      ["Parti de Gauche Val d'Oise", "Le Parti de Gauche Val d'Oise"],
      ["Parti de Gauche de Seine-Saint-Denis", "Le Parti de Gauche de Seine-Saint-Denis"],
      ["Parti de Gauche de la Côte d'or", "Le Parti de Gauche de la Côte d'or"],
      ["Parti de Gauche de la Sarthe", "Le Parti de Gauche de la Sarthe"],
      ["Parti de Gauche du Bas-Rhin", "Le Parti de Gauche du Bas-Rhin"],
      ["Parti de Gauche du Bas-Rhin (67)", "Le Parti de Gauche du Bas-Rhin (67)"],
      ["Parti de Gauche du Gard", "Le Parti de Gauche du Gard"],
      ["Parti de Gauche du Gard (30)", "Le Parti de Gauche du Gard (30)"],
      ["Parti de Gauche et 15 autres organisations", "Le Parti de Gauche et 15 autres organisations"],
      ["PascalGassiot", "Pascal Gassiot"],
      ["Pascale Le Neouannic", "Pascale Le Néouannic"],
      ["Pascale Le Neouannic et François Cocq", "Pascale Le Néouannic et François Cocq"],
      ["Pascale Le Néhouanic", "Pascale Le Néouannic"],
      ["Pascale Leneouanic", "Pascale Le Néouannic"],
      ["Pascale le Neouannic", "Pascale Le Néouannic"],
      ["Pascale le Neouannic et Laurence Pache", "Pascale Le Néouannic et Laurence Pache"],
      ["Pascale le Neouannic, secrétaire nationale et Thomas Linard, responsable commission LGBT du Parti de Gauche", "Pascale Le Néouannic, secrétaire nationale et Thomas Linard, responsable commission LGBT du Parti de Gauche"],
      ["Patrice Perderereau", "Patrice Perdereau"],
      ["Paul ARIES", "Paul Ariès"],
      ["Paul Aries", "Paul Ariès"],
      ["Philippe Muhlstein", "Philippe Mühlstein"],
      ["Philippe VILLETARD", "Philippe Villetard"],
      ["Pierre CARASSUS", "Pierre Carassus"],
      ["Pierre CHANTELOT", "Pierre Chantelot"],
      ["Pierre HOUQUES", "Pierre Houques"],
      ["Pour le Parti de Gauche 67, Josiane Nervi-Gasparini, Jean-Claude Val", "Parti de Gauche 67, Josiane Nervi-Gasparini, Jean-Claude Val"],
      ["Raquel GARRIDO", "Raquel Garrido"],
      ["Raquel garrido", "Raquel Garrido"],
      ["Raquel Garrido et Alexis Corbiere", "Raquel Garrido et Alexis Corbière"],
      ["René REVOL", "René Revol"],
      ["Robert INJEY et Roselyne GRAC", "Robert Injey et Roselyne Grac"],
      ["Robert SPIZZICHINO", "Robert Spizzichino"],
      ["Roeslyne GRAC et Jean SADOUX", "Roselyne Grac et Jean Sadoux"],
      ["SN", "Secrétariat National du Parti de Gauche"],
      ["SN du PG", "Secrétariat National du Parti de Gauche"],
      ["Secrétariat National", "Secrétariat National du Parti de Gauche"],
      ["Secrétariat National du PG", "Secrétariat National du Parti de Gauche"],
      ["Secrétariat national", "Secrétariat National du Parti de Gauche"],
      ["Secrétariat national du PG", "Secrétariat National du Parti de Gauche"],
      ["Secrétariat national du Parti de Gauche", "Secrétariat National du Parti de Gauche"],
      ["Sophie CHAPELLE", "Sophie Chapelle"],
      ["Sylvaine ETTORI", "Sylvaine Ettori"],
      ["Thibault GRAC", "Thibault Grac"],
      ["Thierry BRUN", "Thierry Brun"],
      ["Thierry THIBAULT", "Thierry Thibault"],
      ["Yvan DUPONT", "Yvan Dupont"],
      ["agauchepourdevrai", "agauchepourdevrai.fr"],
      ["brigitte blang pg57", "Brigitte Blang pg57"],
      ["commission Justice et liberté du PG", "Commission Justice et liberté"],
      ["dei Lenk", "Dei Lénk"],
      ["die Linke", "Die Linke"],
      ["eric coquerel", "Eric Coquerel"],
      ["groupe GUE/NGL", "Groupe GUE/NGL"],
      ["l'Humanité.fr|", "humanite.fr|"],
      ["la télé de gauche", "La Télé de Gauche"],
      ["Télé de Gauche", "La Télé de Gauche"],
      ["Télé de gauche", "La Télé de Gauche"],
      ["Radio de Gauche", "La Radio de Gauche"],
      ["le Parti de Gauche 44, le NPA 44 et les Alternatifs 44", "Parti de Gauche 44, NPA 44 et Alternatifs 44"],
      ["résolution du PGE", "Résolution du PGE"],
      [" Bruno Roger-Petit - Chroniqueur politique LE PLUS", "Bruno Roger-Petit, chroniqueur politique LE PLUS"],
      ["Éloïse Lebourg", "Eloïse Lebourg"],
      ["Éric Coquerel", "Eric Coquerel"],
      ["Éric Coquerel, Secrétaire national du Parti de Gauche", "Eric Coquerel, Secrétaire national du Parti de Gauche"],
      ["réseau bi-régional Amérique latine et Caraïbe", "Réseau bi-régional Amérique latine et Caraïbe"],
      ["signatures en fin d'article", "Signatures en fin d'article"],
      ["traduction: Jean – PCWB", "Traduction : Jean – PCWB"],
      ["trad. Guillaume Beaulande", "Trad. Guillaume Beaulande"],
      ["Trad : Bruno Fialho", "Traduction : Bruno Fialho"],
      ["Trad : David Maréchal", "Traduction : David Maréchal"],
      ["Trad : Françoise Bague", "Traduction : Françoise Bague"],
      ["Trad : Françoise Bague et D.M.G", "Traduction : Françoise Bague et D.M.G"],
      ["Trad : Françoise Bague et Juliette Hamelin", "Traduction : Françoise Bague et Juliette Hamelin"],
      ["Trad : Guillaume Beaulande", "Traduction : Guillaume Beaulande"],
      ["Trad Guillaume Beaulande", "Traduction : Guillaume Beaulande"],
      ["Trad. : Alex Tessereau", "Traduction : Alex Tessereau"],
      ["Trad. : Bruno Fialho", "Traduction : Bruno Fialho"],
      ["Trad. : Erio Barale-Thomas", "Traduction : Erio Barale-Thomas"],
      ["Trad. : Françoise Bague", "Traduction : Françoise Bague"],
      ["Trad. : Guillaume Beaulande", "Traduction : Guillaume Beaulande"],
      ["Trad. : Mario Morisi", "Traduction : Mario Morisi"],
      ["Trad. Antoine Garcia", "Traduction : Antoine Garcia"],
      ["Trad. Céline Meneses et Sigrid Melanchthon", "Traduction : Céline Meneses et Sigrid Melanchthon"],
      ["Trad. Françoise Bague", "Traduction : Françoise Bague"],
      ["Trad. Guillaume Beaulande", "Traduction : Guillaume Beaulande"],
      ["Traducteur : DMG", "Traduction : DMG"],
      ["Traducteur : Guillaume Beaulande", "Traduction : Guillaume Beaulande"],
      ["Traducteur: Guillaume beaulande", "Traduction : Guillaume beaulande"],
      ["Traduction : Françoise Bague et Juliette Estivill", "Traduction : Françoise Bague et Juliette Estivill"],
      ["Traduction : Françoise bague", "Traduction : Françoise bague"],
      ["Traduction : Guillaume Beaulande et Céline Meneses", "Traduction : Guillaume Beaulande et Céline Meneses"],
      ["Traduction : Guillaume Beaulande et Juliette Estivill", "Traduction : Guillaume Beaulande et Juliette Estivill"],
      ["Traduction : Mario Morisi", "Traduction : Mario Morisi"],
      ["Traduction: Françoise Bague", "Traduction : Françoise Bague"],
      ["Traduction: Guillaume Beaulande", "Traduction : Guillaume Beaulande"],
      ["Traduction: Jean – PCWB", "Traduction : Jean – PCWB"],
      ["Traductrice : Françoise Bague", "Traduction : Françoise Bague"],
      ["Traductrice : Juliette Hamelin", "Traduction : Juliette Hamelin"],
      ["Front de Gauche", "Le Front de Gauche"],
      ["Parti de Gauche", "Le Parti de Gauche"]
    ]
      ActiveRecord::Base.connection.execute "update articles set signature = #{Article.quote(signature[1])} where signature = #{Article.quote(signature[0])}"
    end
  end
end