# encoding: utf-8
# PGonror is the corporate web site framework of Le Parti de Gauche based on Ruby on Rails.
# 
# Copyright (C) 2013 Le Parti de Gauche
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# 
# See doc/COPYRIGHT.rdoc for more details.

# Configures the supported types of content (categories) for articles.
# The first element defines the displayed label of the article category.
# The second element defines the stored article category code.
# The third element defines options that apply for the article category.
#  :signature (boolean) includes a signature to articles.
#  :parent (boolean) sets the category as a parent for other categories (as folders). 
#  :source (boolean) sets the category as a source of information for other categories.
#  :image (boolean) sets the category as a reference to an image.
#  :document (boolean) sets the category as a reference to a document.
#  :controller sets the controller used in the website to display the article of the same category.
#  :action_all sets the action used in the website to display the list of article of the same category.
#  :action sets the action used in the website to display one article of the same category.
#  :category_title sets the title of category to be displayed in the website.
#  :link_all_title sets the title of a link to a list of article of the same category to be displayed in the website.
#  :start_end_dates includes a start and a end date and time.
#  :audio indicates the content is an audio file.
#  :video indicates the content is a video.
#  :militer indicates the content is for activism.
#  :searchable includes the article category in the searches.
#  :unfeedable excludes the article category from the feeds.
#  :access_level is related to the access to public or protected users.
#  :email defines an email address attached to the category.
#  :hide_category_name hides the name of the category.
CATEGORIES = [
              ["À GAUCHE", 'presentation_agauche'],
              ["ACTUALITÉ", 'actu', {:signature => true,
                                     :searchable => true,
                                     :controller => '/actualites',
                                     :action_all => :actualites,
                                     :action => :actualite,
                                     :description => "Actualités du Parti de Gauche",
                                     :category_title => "ACTUALITÉS",
                                     :link_all_title => "LIRE TOUTES LES ACTUALITÉS"}],
              ["ADHÉSION", 'adhesion', {:unfeedable => true,
                                        :controller => '/memberships',
                                        :action_all => :adhesion}],
              ["AFFICHE", 'affiche', {:militer => true,
                                      :searchable => true,
                                      :controller => '/militer',
                                      :action_all => :affiches,
                                      :action => :affiche,
                                      :description => "Affiches du Parti de Gauche",
                                      :category_title => "AFFICHES",
                                      :link_all_title => "VOIR TOUTES LES AFFICHES"}],
              ["AGIT’PROP", 'videoagitprop', {:signature => true,
                                              :searchable => true,
                                              :video => true,
                                              :unfeedable => true,
                                              :controller => '/videos',
                                              :action_all => :videosagitprop,
                                              :action => :agitprop,
                                              :description => "Vidéos agit’prop du Parti de Gauche",
                                              :category_title => "VIDÉOS AGIT’PROP",
                                              :link_all_title => "TOUTES LES VIDÉOS AGIT’PROP"}],
              ["ARGUMENT", 'argument', {:signature => true,
                                        :searchable => true,
                                        :controller => '/arguments',
                                        :action_all => :arguments,
                                        :action => :argument,
                                        :description => "Arguments du Parti de Gauche",
                                        :category_title => "ARGUMENTS",
                                        :link_all_title => "LIRE TOUS LES ARGUMENTS"}],
              ["ARTICLE DIVERS (NON CLASSÉ)", 'divers'],
              ["ARTICLE VIE DE GAUCHE", 'articlevdg', {:signature => true,
                                                       :searchable => true,
                                                       :controller => '/viedegauche',
                                                       :action_all => :index,
                                                       :action => :article,
                                                       :description => "Articles vie de gauche du Parti de Gauche",
                                                       :category_title => "VIE DE GAUCHE",
                                                       :link_all_title => "VOIR TOUS LES ARTICLES"}],
              ["BLOG", 'blog', {:searchable => true,
                                :source => true,
                                :controller => '/vudailleurs',
                                :action_all => :blogs,
                                :action => :blog,
                                :description => "Blogs du Parti de Gauche",
                                :category_title => "BLOGS",
                                :link_all_title => "ACCÉDER À LA LISTE DES BLOGS"}],
              ["CAMPAGNE", 'campagne', {:hide_category_name => true,
                                        :controller => '/militer',
                                        :action_all => :index,
                                        :description => "Campagnes du Parti de Gauche",
                                        :category_title => "CAMPAGNE"}],
              ["CAMPAGNE EN LIGNE", 'campagne_enligne', {:searchable => true,
                                                         :controller => '/militer',
                                                         :action_all => :index,
                                                         :description => "Campagnes en ligne du Parti de Gauche",
                                                         :category_title => "CAMPAGNES EN LIGNE"}],
              ["CIRCULAIRE ADHÉRENTS", 'circulaire', {:access_level => :reserved,
                                                      :controller => '/adherent',
                                                      :action_all => :index,
                                                      :action => :article}],
              ["COMMISSION FONCTIONNELLE", 'commission_fonc', {:email => true}],
              ["COMMISSION THÉMATIQUE", 'commission_them', {:email => true}],
              ["COMMUNIQUÉ", 'com', {:signature => true,
                                     :searchable => true,
                                     :controller => '/actualites',
                                     :action_all => :communiques,
                                     :action => :communique,
                                     :description => "Communiques du Parti de Gauche",
                                     :category_title => "COMMUNIQUÉS",
                                     :link_all_title => "LIRE TOUS LES COMMUNIQUÉS"}],
              ["CONFÉRENCE ET DISCOURS", 'conference', {:signature => true,
                                                        :searchable => true,
                                                        :video => true,
                                                        :unfeedable => true,
                                                        :controller => '/videos',
                                                        :action_all => :conferences,
                                                        :action => :conference,
                                                        :description => "Conférences et discours du Parti de Gauche",
                                                        :category_title => "CONFÉRENCES ET DISCOURS",
                                                        :link_all_title => "TOUTES LES CONFÉRENCES ET DISCOURS"}],
              ["CONSEIL", 'conseil', {:access_level => :reserved,
                                      :controller => '/adherent',
                                      :action_all => :index,
                                      :action => :article}],
              ["CONTACT", 'contact', {:controller => '/contact',
                                      :action_all => :index,
                                      :action => :index,
                                      :description => "Contact du Parti de Gauche",
                                      :category_title => "CONTACTS"}],
              ["CONTACT COMITÉ", 'departement', {:searchable => true,
                                                 :source => true, 
                                                 :controller => '/contact',
                                                 :action_all => :index,
                                                 :action => :departement,
                                                 :description => "Contacts comités du Parti de Gauche",
                                                 :category_title => "POUR CONTACTER LE PARTI DE GAUCHE PRES DE CHEZ VOUS"}],
              ["C’EST ARRIVÉ PRÈS DE CHEZ VOUS", 'videoevenement', {:signature => true,
                                                                    :searchable => true,
                                                                    :video => true,
                                                                    :unfeedable => true,
                                                                    :controller => '/videos',
                                                                    :action_all => :videospresdechezvous,
                                                                    :action => :presdechezvous,
                                                                    :description => "Vidéos arrivées près de chez vous du Parti de Gauche",
                                                                    :category_title => "C’EST ARRIVÉ PRÈS DE CHEZ VOUS",
                                                                    :link_all_title => "TOUT CE QUI EST ARRIVÉ"}],
              ["DIAPORAMA", 'diaporama', {:parent => true,
                                          :searchable => true,
                                          :controller => '/photos',
                                          :action_all => :index,
                                          :action => :diaporama,
                                          :description => "Diaporams du Parti de Gauche",
                                          :category_title => "DIAPORAMAS",
                                          :link_all_title => "TOUS LES DIAPORAMAS"}],
              ["DIRECT DE BLOG", 'directblog', {:signature => true,
                                                :searchable => true,
                                                :controller => '/vudailleurs',
                                                :action_all => :articlesblog,
                                                :action => :articleblog,
                                                :description => "Article de blog du Parti de Gauche",
                                                :category_title => "EN DIRECT DES BLOGS",
                                                :link_all_title => "VOIR TOUS LES ARTICLES"}],
              ["DOCUMENT", 'document', {:document => true,
                                        :unfeedable => true}],
              ["DOCUMENT UTILE", 'doc-utile', {:access_level => :reserved,
                                               :controller => '/adherent',
                                               :action_all => :index,
                                               :action => :article}],
              ["DON", 'don', {:unfeedable => true,
                              :controller => '/donations',
                              :action_all => :don}],
              ["DOSSIER", 'dossier', {:signature => true,
                                      :searchable => true,
                                      :controller => '/actualites',
                                      :action_all => :dossiers,
                                      :action => :dossier,
                                      :description => "Dossiers du Parti de Gauche",
                                      :category_title => "DOSSIERS",
                                      :link_all_title => "VOIR TOUS LES DOSSIERS"}],
              ["ÉDITO", 'edito', {:signature => true,
                                  :searchable => true,
                                  :controller => '/actualites',
                                  :action_all => :editos,
                                  :action => :edito,
                                  :description => "Éditos du Parti de Gauche",
                                  :category_title => "ÉDITOS",
                                  :link_all_title => "LIRE TOUS LES ÉDITOS"}],
              ["ÉDUC POP", 'videoeduc', {:signature => true,
                                         :searchable => true,
                                         :video => true,
                                         :unfeedable => true,
                                         :controller => '/videos',
                                         :action_all => :touteducpop,
                                         :action => :educpop,
                                         :description => "Vidéos éduc pop du Parti de Gauche",
                                         :category_title => "VIDÉOS ÉDUC POP",
                                         :link_all_title => "TOUTES LES VIDÉOS ÉDUC POP"}],
              ["EN CAMPAGNE", 'encampagne', {:signature => true,
                                             :searchable => true,
                                             :video => true,
                                             :unfeedable => true,
                                             :controller => '/videos',
                                             :action_all => :videosencampagne,
                                             :action => :encampagne,
                                             :description => "Vidéos de campagne du Parti de Gauche",
                                             :category_title => "VIDÉOS EN CAMPAGNE",
                                             :link_all_title => "TOUTES LES VIDÉOS EN CAMPAGNE"}],
              ["ÉVÉNEMENT", 'evenement', {:searchable => true,
                                          :unfeedable => true,
                                          :start_end_dates => true,
                                          :controller => '/militer',
                                          :action_all => :agenda,
                                          :action => :evenement,
                                          :description => "Agenda du Parti de Gauche",
                                          :category_title => "AGENDA",
                                          :link_all_title => "VOIR L’AGENDA"}],
              ["GAVROCHE", 'presentation_gavroche'],
              ["IDENTITÉ", 'identite', {:controller => '/quisommesnous',
                                        :action_all => :index,
                                        :action => :identite,
                                        :description => "Journal du réseau jeune du Parti de Gauche",
                                        :category_title => "IDENTITÉ"}],
              ["IMAGE", 'image', {:image => true,
                                  :unfeedable => true,
                                  :signature => true,
                                  :controller => '/photos',
                                  :action_all => :index,
                                  :description => "Images du Parti de Gauche",
                                  :category_title => "PHOTOS",
                                  :link_all_title => "VOIR TOUTES LES PHOTOS"}],
              ["INSTANCE NATIONALE", 'instance', {:searchable => true,
                                                  :source => true,
                                                  :controller => '/quisommesnous',
                                                  :action_all => :index,
                                                  :action => :instance,
                                                  :description => "Instances nationales du Parti de Gauche",
                                                  :category_title => "INSTANCES NATIONALES"}],
              ["INTERNATIONAL", 'inter', {:signature => true,
                                          :searchable => true,
                                          :controller => '/actualites',
                                          :action_all => :tout_international,
                                          :action => :international,
                                          :description => "Articles internationaux du Parti de Gauche",
                                          :category_title => "INTERNATIONAL",
                                          :link_all_title => "TOUT L’INTERNATIONAL"}],
              ["JOURNAL VIE DE GAUCHE", 'vdg', {:searchable => true,
                                                :controller => '/viedegauche',
                                                :action_all => :journauxvdg,
                                                :action => :journalvdg,
                                                :description => "Journaux Vie de Gauche du Parti de Gauche",
                                                :category_title => "JOURNAL VIE DE GAUCHE",
                                                :link_all_title => "VOIR LES ARCHIVES"}],
              ["LETTRE", 'lecture', {:searchable => true,
                                     :controller => '/educpop',
                                     :action_all => :lectures,
                                     :action => :lecture,
                                     :description => "Lettres du Parti de Gauche",
                                     :category_title => "LETTRES",
                                     :link_all_title => "TOUTES LES LETTRES"}],
              ["LÉGISLATIVES : CE QUE L’ON VEUT !", 'legislative', {:signature => true,
                                                                    :searchable => true,
                                                                    :controller => '/arguments',
                                                                    :action_all => :legislatives,
                                                                    :action => :legislative,
                                                                    :description => "Questions législatives du Parti de Gauche",
                                                                    :category_title => "LEGISLATIVES",
                                                                    :link_all_title => "LIRE TOUTES LES QUESTIONS"}],
              ["LETTRE D’INFORMATION", 'information'],
              ["KIT ET BROCHURE", 'kit', {:militer => true,
                                          :searchable => true,
                                          :controller => '/militer',
                                          :action_all => :kits,
                                          :action => :kit,
                                          :description => "Kits et brochures militants du Parti de Gauche",
                                          :category_title => "KITS ET BROCHURES",
                                          :link_all_title => "VOIR TOUS LES KITS ET BROCHURES"}],
              ["LIVRE MILITANT", 'livre', {:searchable => true,
                                           :controller => '/educpop',
                                           :action_all => :librairie,
                                           :action => :livre,
                                           :description => "Librairie militante du Parti de Gauche",
                                           :category_title => "LIBRAIRIE MILITANTE",
                                           :link_all_title => "DÉCOUVRIR TOUTES LES PARUTIONS"}],
              ["MÉDIA", 'media', {:signature => true,
                                  :searchable => true,
                                  :video => true,
                                  :unfeedable => true,
                                  :controller => '/videos',
                                  :action_all => :medias,
                                  :action => :media,
                                  :description => "Passages média du Parti de Gauche",
                                  :category_title => "MÉDIAS",
                                  :link_all_title => "TOUS LES PASSAGES MÉDIA"}],
              ["MENTIONS LÉGALES", 'legal', {:unfeedable => true,
                                             :controller => '/accueil',
                                             :action_all => :legal}],
              ["PÔLES ET COMMISSIONS", 'commission', {:searchable => true,
                                                      :controller => '/quisommesnous',
                                                      :action_all => :index,
                                                      :action => :commission,
                                                      :description => "Pôles et commissions du Parti de Gauche",
                                                      :category_title => "PÔLES ET COMMISSIONS"}],
              ["PROGRAMME", 'programme', {:signature => true,
                                          :searchable => true,
                                          :controller => '/arguments',
                                          :action_all => :leprogramme,
                                          :action => :programme,
                                          :description => "Programme partagé du Parti de Gauche",
                                          :category_title => "PROGRAMME PARTAGÉ",
                                          :link_all_title => "LIRE LE PROGRAMME"}],
              ["RÉPERTOIRE", 'directory', {:parent => true, :unfeedable => true}],
              ["REVUE", 'revue', {:searchable => true,
                                  :controller => '/educpop',
                                  :action_all => :revues,
                                  :action => :revue,
                                  :description => "Revues À GAUCHE du Parti de Gauche",
                                  :category_title => "REVUES À GAUCHE",
                                  :link_all_title => "VOIR TOUS LES NUMÉROS"}],
              ["TRACT ET LOGO", 'tract', {:militer => true,
                                          :searchable => true,
                                          :controller => '/militer',
                                          :action_all => :tracts,
                                          :action => :tract,
                                          :description => "Tracts et logos du Parti de Gauche",
                                          :category_title => "TRACTS ET LOGOS",
                                          :link_all_title => "TOUS LES TRACTS ET LOGOS"}],
              ["UNE DATE, UN JOUR", 'date', {:signature => true,
                                             :searchable => true,
                                             :controller => '/educpop',
                                             :action_all => :dates,
                                             :action => :date,
                                             :description => "Articles une date, un jour du Parti de Gauche",
                                             :category_title => "UNE DATE, UN JOUR",
                                             :link_all_title => "VOIR LES ARCHIVES"}],
              ["RADIO DE GAUCHE", 'son', {:audio => true,
                                          :signature => true,
                                          :searchable => true,
                                          :controller => '/podcast',
                                          :action_all => :index,
                                          :action => :son,
                                          :description => "La Radio du Parti de Gauche",
                                          :storage => "audios",
                                          :category_title => "RADIO DE GAUCHE",
                                          :link_all_title => "TOUS LES ÉPISODES"}],
              ["VIDÉO", 'video', {:signature => true,
                                  :searchable => true,
                                  :video => true,
                                  :unfeedable => true,
                                  :controller => '/videos',
                                  :action_all => :index,
                                  :action => :video,
                                  :description => "Vidéos du Parti de Gauche",
                                  :category_title => "VIDÉOS",
                                  :link_all_title => "VOIR TOUTES LES VIDÉOS"}],
              ["VIDÉO VUE SUR LE WEB", 'videoweb', {:signature => true,
                                                    :searchable => true,
                                                    :video => true,
                                                    :unfeedable => true,
                                                    :controller => '/videos',
                                                    :action_all => :toutweb,
                                                    :action => :web,
                                                    :description => "Vidéos vues sur le web",
                                                    :category_title => "VIDÉOS VUES SUR LE WEB",
                                                    :link_all_title => "TOUTES LES VIDÉOS VUES SUR LE WEB"}],
              ["VU D’AILLEURS", 'web', {:signature => true,
                                        :searchable => true,
                                        :controller => '/vudailleurs',
                                        :action_all => :articlesweb,
                                        :action => :articleweb,
                                        :description => "Articles vu d’ailleurs du Parti de Gauche",
                                        :category_title => "VU D’AILLEURS",
                                        :link_all_title => "VOIR TOUS LES ARTICLES"}]
] unless defined?(CATEGORIES)
